version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.30
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=api
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 40s
      retries: 10
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./redis_data:/data

  focusider:
    container_name: spring
    ports:
      - "8080:8080"
    image: mango0422/focusider:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/api
      SPRING_DATASOURCE_USERNAME: "api"
      SPRING_DATASOURCE_PASSWORD: "api"
