version: "3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=focusider!
      - MYSQL_DATABASE=focusider
      - MYSQL_USER=focusider
      - MYSQL_PASSWORD=focusider!
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 40s
      retries: 10
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - focusider-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Redis 기본 포트 수정
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - focusider-network

  focusider:
    container_name: spring
    ports:
      - "8080:8080"
    image: mango0422/focusider:latest
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/focusider
      SPRING_DATASOURCE_USERNAME: "focusider"
      SPRING_DATASOURCE_PASSWORD: "focusider!"
    networks:
      - focusider-network

networks:
  focusider-network:
    driver: bridge
