spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/focuside?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: '1918'

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  jackson:
    time-zone: Asia/Seoul

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379
      password:
    rest:
      detection-strategy: annotated

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  jwt:
    secret: 035181ea40e854b3a37b714bcf6c99f0df16e3040c3f65be4a0123032e00ee75fef03f85461cf71db7f535ae1cffbc248186b2e6f1e55b63dc5255183015bda6
    expireAccessToken: 1800000
    expireRefreshToken: 604800000

cloud:
  aws:
    s3:
      bucket: focusider
      upload-path: https://focusider-s3.s3.ap-northeast-2.amazonaws.com
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA6GBMDCUSSCFIK2VH
      secret-key: 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

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: trace

openapi:
  service:
    url: localhost:8080

springdoc:
  version: 0.0.1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html