spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  jackson:
    time-zone: Asia/Seoul

  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true
    redis:
      host: redis
      port: 6379
      password:
    rest:
      detection-strategy: annotated

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  jwt:
    secret: ${JWT_SECRET}
    expireAccessToken: 1800000
    expireRefreshToken: 604800000
  ai:
    openai:
      api-key: ${OPENAI_KEY} # Replace with your actual OpenAI API key
      chat:
        options:
          model: gpt-4o-mini # The OpenAI model to use (e.g., gpt-3.5-turbo or gpt-4)
          temperature: 0.7 # Adjust the temperature for response creativity (0.0 - 1.0)
          max-tokens: 1000 # Set the maximum number of tokens to generate in a response
          top-p: 1.0 # Controls diversity via nucleus sampling
          n: 1 # Number of responses to return
          stop: null # Specify stop sequences for responses (optional)
          presence-penalty: 0.0 # Penalize new topics in generation (0.0 for no penalty)
          frequency-penalty: 0.0 # Penalize repeated phrases in generation (0.0 for no penalty)

cloud:
  aws:
    s3:
      bucket: focusider
      upload-path: ${S3_URL}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: trace

openapi:
  service:
    url: localhost:8080

springdoc:
  version: 0.0.1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html
