name: pnpm build test for merge on devlop

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted
    name: Build and Deploy on EC2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Build
        run: /gradlew build
